### ISSUE TITLE
The correctness of the spectrum？

### ISSUE THREAD

**Issue by WHYAOAOAO** [fispact/actigamma#7]
How do you ensure the correctness of the drawn energy spectrum? Have you verified it with someone else's paper or software or measured energy spectrum?

**Comment by thomasms** [comment]
For future reference, I would suggest we move this to a discussion (https://github.com/fispact/actigamma/discussions) and other similar questions, instead of creating an issue every time. But for this time I will address this question here.

I assume you are referring to the correctness of the plot not the data itself, since you mention "drawn", if not, please correct me. In that case, there must be a specific example, which again, it would be good for you to point to it here. I will assume one of the simple plots (gamma spectrum 1D histogram as a function of energy) i.e. this example: https://github.com/fispact/actigamma/blob/master/examples/plotlines.py for the purposes of this discussion.

As you can see from this script, there really is nothing special going on for the drawing part, it is a simple plot using matplotlib. The only thing going on here before this is this bit:
```python
X, Y = ag.getplotvalues(bin_edges, hist)
```
Which is also a simple function to make a histogram like plot, see here: https://github.com/fispact/actigamma/blob/master/actigamma/util.py

All in all, there is really nothing going on for the drawing part and it is very easy to verify for yourself.

The important bit here is that the data is accurate and this is where a lot of effort has been on the validation. There are numerous unit tests in place to check the energy grid, inventory, and the database (see here: https://github.com/fispact/actigamma/tree/master/tests) these run for every change to the code. The other validation part is the source of the data, and here pypact was used to parse it from FISPACT-II, of which both codes have been extensively tested both automatically and manually.

I would suggest if you are not confident in the data or the examples, then you can simply ignore this package. Otherwise, if you would like to contribute or verify some of the spectra, that would be greatly appreciated.
